### ISSUE TITLE
Need ability to set the height on events in month view

### ISSUE THREAD

**Issue by sheam** [nathanstitt/dayz#13]
I have a monthly calendar with 2 week long all-day events.

There doesn't seem to be a way to set the height of the events. I tried setting the CSS class for the  div.event to be 60px, but JS seems to calc the top margin incorrectly then as if it was still set to 20px.

The weird thing is that it only messes this up for the first part of the event.

See screenshot:

![dayz](https://user-images.githubusercontent.com/1779211/36621487-d75e5b90-18bd-11e8-8129-4796a47eec3f.png)

**Comment by sheam** [comment]
Changing line 115 of dayz.scss from 
`&.stack-#{$stack} { margin-top: ($stack) * $dayz-event-height; }`
to
`&.stack-#{$stack} { margin-top: ($stack) * $dayz-event-height; }`
solved the problem.

**Comment by nathanstitt** [comment]
Hm, right you are.  I'd missed using the variable there.  I also noticed that I was using the same variable to set the label heights which looked weird when set to 60px.

I've just released `0.8.1` with this change and the scripts.  Give that a shot and see how it works for you.

Thanks for using `dayz` 😁
