### ISSUE TITLE
npm scripts don't run on windows

### ISSUE THREAD

**Issue by sheam** [nathanstitt/dayz#15]

**Comment by sheam** [comment]
Changeing the prepublish and  preversion to `"bash ./script/prepublish"` works, but of cource depends on bash existing on the dev machine.

**Comment by nathanstitt** [comment]
Hm, I don't have much experience with scripting on windows, but based on https://www.howtogeek.com/261591/how-to-create-and-run-bash-shell-scripts-on-windows-10/ `!#/bin/bash` should work on windows 10 at least.

I've changed the scripts to use that in hopes it'll help
