### ISSUE TITLE
Background color for "today"

### ISSUE THREAD

**Issue by javiercerdas** [nathanstitt/dayz#18]
Hi,
I'm hoping this is just an oversight and lack of understanding the component, but is there a way to have a different background color for "today" (in the month view)?  I was looking through the css and I don't see anything to handle "today".  Thank you!

**Comment by Req** [comment]
This is done in the Demo by hilighting an option with the **highlightDays** property.

I would argue that there is a genuine need for classes to target past, present and future days for nicer formatting. I had a look at the codebase to do it myself, but the code looked so foreign it would take me dayz to do - time which I don't have.

**Comment by nathanstitt** [comment]
Thanks for the suggestion!  I've added a "current", "before" and "after" css classes, however they're not styled by default since I think each users will have a different expectation for how they'd be styled.
