### ISSUE TITLE
Tutorial out of date

### ISSUE THREAD

**Issue by JoelKlint** [nathanstitt/dayz#2]
Hi,

I'm trying out the calendar but cant get it too work. It renders without any problem but the result is not as expected. I am not sure whether something is broken or I have just missed something. I am using React 15.0.2. 

I have tried both copy pasting the tutorial and rewriting it using ES6 syntax. Currently my code looks like this:
```js
import React from 'react';
import Dayz from 'dayz';
import moment from 'moment';

export default class TestDayz extends React.Component {

	constructor(props) {
		super();
		const events = new Dayz.EventsCollection([
			{ content: 'A short event',
				range: moment.range( moment(), moment().add(1, 'day') )
			}
		]);
		this.state = {events}
	}

	render() {
		return (
			<Dayz
				date={moment()}
				events={this.state.events}
			/>
		)
	}
}
```
and this is the result
![screen shot 2016-05-11 at 12 07 35](https://cloud.githubusercontent.com/assets/6799000/15177725/df0fc224-1771-11e6-85db-a33b4097f109.png)

**Comment by RobbyRob81** [comment]
I'm pretty sure this no longer works.  I've spend a few days trying to get it to work as well.

**Comment by JoelKlint** [comment]
Excellent, thanks!
