### ISSUE TITLE
[Question] Why are babel libs included as dependencies?

### ISSUE THREAD

**Issue by arecvlohe** [nathanstitt/dayz#20]
@jalpedersen Great library! I was just wondering why these are listed as dependencies?

```json
"@babel/core": "^7.1.6",
"@babel/preset-env": "^7.1.6",
"@babel/preset-react": "^7.0.0",
"babel-core": "^7.0.0-bridge.0",
```

I'd be happy to submit a PR to update these to `devDependencies` unless they are needed as `dependencies`. It doesn't seem like that would be the case if the library is bundled using webpack.

**Comment by nathanstitt** [comment]
Hey @arecvlohe, great catch, I don't know why those are direct dependencies, they should only be dev dependencies.

I'll release a new version without them shortly
