### ISSUE TITLE
Turn all day events into single day events

### ISSUE THREAD

**Issue by rkorzeniec** [nathanstitt/dayz#25]
First of all thanks for the great work on the component. On my fork of your repo I made an option to display the all day events as a full day (if needed multiple) day events. 
Currently it is like so:
<img width="1280" alt="Screenshot 2019-08-23 at 21 11 54" src="https://user-images.githubusercontent.com/12559188/63617794-aef7b800-c5ea-11e9-930e-eed2abe37998.png">

After the proposed change:
<img width="1280" alt="Screenshot 2019-08-23 at 21 12 06" src="https://user-images.githubusercontent.com/12559188/63617803-b323d580-c5ea-11e9-8387-ad6a741f1467.png">

@nathanstitt would you consider this kind of change?

**Comment by rkorzeniec** [comment]
Yes, my plan was to pass on a variable (most likely to the `EventsCollection`) in order to give choice to keep the calendar as is or split the events. 

I'm glad you like the idea, I will continue with the implementation and then open the PR

**Comment by nathanstitt** [comment]
Just released as `2.6.0`.  Thanks again!
