### ISSUE TITLE
Any option to limit the number of displayed events

### ISSUE THREAD

**Issue by phamvuau** [nathanstitt/dayz#31]
How can I achieve this behavior with dayz?

<img width="468" alt="Screen Shot 2019-12-26 at 10 24 35 AM" src="https://user-images.githubusercontent.com/259848/71456047-2c664b80-27ca-11ea-8749-506af8b9bd2d.png">

**Comment by nathanstitt** [comment]
Sorry but there really isn't any out of the box behavior to accomplish that.  

You might be able to get close by limiting the height of the container and then adding a `:after` css pseudo element but that's completely untested
