### ISSUE TITLE
Y Label time format is not configurable

### ISSUE THREAD

**Issue by Geeman201** [nathanstitt/dayz#4]
Currently the left Y labels time format on the 'day' view is set to `ha` could this perhaps be configurable through an additional prop? 

`timeFormat="hh:mm"` for example?

**Comment by nathanstitt** [comment]
great idea and implemented in https://github.com/nathanstitt/dayz/pull/5

**Comment by nathanstitt** [comment]
Hi @Geeman201, i just published `0.7`.  Give that a shot when you get a chance.  Thanks again for the update!
