### ISSUE TITLE
0.7.0 Build issue

### ISSUE THREAD

**Issue by Geeman201** [nathanstitt/dayz#6]
Hey @nathanstitt, me again!! 

Just updated to v0.7.0 and I'm getting the following issue:
```
Module not found: Can't resolve 'dayz'
```

After doing some digging/debugging I think the issue is just with how the 0.7.0 package was built/published to the npm registry.

I believe the issue is that the package pushed to the npm registry doesn't contain the prebuilt `dist` directory. As the `package.json` also points to `dist/dayz.js` I think the package just needs to be repushed with the `dist` directory included.

When I pull the git repository, run `npm install` and copy the `dist/dayz.js` file into my project it worked just great. 

Hope you can help,
James

**Comment by nathanstitt** [comment]
Hi @Geeman201 - Thanks so much for letting me know I'd bungled the release.  Appears I was using nom link locally so I didn't notice 😊 

I then ran into a rollup config issue so it took me a few tries, `0.7.3` should be good to go though.

Please let me know if you hit any other issues.

**Comment by Geeman201** [comment]
@nathanstitt FYI this works great now :) and a good idea to bump to 0.8.0 I think! 

I've raised a PR to correct the small mistake in the docs! 

James
