### ISSUE TITLE
Customizing the EventsCollection object or Event display.

### ISSUE THREAD

**Issue by babycourageous** [nathanstitt/dayz#7]
Hi there --

I'm looking into this calendar component and am curious if the structure of the EvnetsCollection object is that it only contains a content and range field. I have an incoming GraphQL API of events that includes an event title, url slug, and event start time that I would like to use...
Are there other fields you can include in the EventsCollection or is there any way to customize the displayed event (like making your own component) using that object.

Thanks!

**Comment by nathanstitt** [comment]
Hi @babycourageous,

Thanks for trying out Dayz!

The `EventsColleciton` collection contains [Events](https://github.com/nathanstitt/dayz/blob/master/src/api/event.js).  It calls `render()` on them to get the element for each day.  I think you should be able to override the [defaultRenderImplementation](https://github.com/nathanstitt/dayz/blob/master/src/api/event.js#L26) with a custom method. 

Something like this should work (may have typos, etc):
```javascript
class MyEvent extends Dayz.EventsCollection.Event {
   def defaultRenderImplementation() {
      return <h1>My Custom Content</h1>;
   } 
}

const collection =  new Dayz.EventsCollection([ 
    new MyEvent({ range: moment.range(new Date(), moment().add(1, 'day') ) }),
]);
```

If you run into trouble with the above send me a codpen or something and I'll try to help further.

**Comment by babycourageous** [comment]
Thanks! - it seems to be working but there is one glitch...

I'm pulling in the GraphQL array in Ascending order. 
I map over those to create each event (i.e. `{content: object of info, range: content.datetime}`)
then call `new Dayz.EventsCollection()` passing in that mapped array of Events.
There is one Event that gets popped out of order and placed at the beginning of the EventsCollection array and so is displaying wrong on the calendar. 

I'm logging each step of the way and it's being mapped in order and passed to Collection in order but after that when logging the whole collection the first item is the entry that should in the middle...
