### ISSUE TITLE
Custom event and calendar styling question

### ISSUE THREAD

**Issue by babycourageous** [nathanstitt/dayz#8]
Hi there

Looking into continuing to modify some of the underlying templates or styling to fit our palette and wondering if the best approach with Dayz is creating new stylesheets (css or scss) that override the classes and declarations or if there are other template wrappers you can override in code (much like the Event override you provided in #7 ). 

thanks again!

**Comment by nathanstitt** [comment]
Hey @babycourageous,

You can style dayz in several different ways.  If you only need to change the colors, the easiest is to import the dayz `scss` files and change the variables https://github.com/nathanstitt/dayz/blob/master/dayz.scss#L1-6

If you're stack isn't setup to easily do that, you can just override the css classes.  I hope I've written the rules to easily allow that, but let me know if you have issues.

**Comment by babycourageous** [comment]
Thanks @nathanstitt  -  

I've been overwriting class declarations in a custom `scss` file. If that is the preferred method I'll continue doing that. However if there are other overrides to hook into like the one you supplied in #7 that would give me more access for adding my own classes or components let me know!

thanks
